---

- name: Creating websites
  tags: website
  webfaction_site:
    name: "{{ item.name }}"
    state: present
    host: "{{ item.host }}"
    subdomains:
      - "{{ item.domain }}"
    site_apps:
      - ["{{ item.app }}", "{{ item.url_path }}"]
    https: "{{ item.https }}"
    login_name: "{{webfaction_user}}"
    login_password: "{{webfaction_passwd}}"
  with_items:
    - "{{ website.main }}"
    - "{{ website.static }}"
    - "{{ website.uploads }}"

- name: Creating insecure redirection websites
  tags: website
  when: item.https
  webfaction_site:
    name: "{{ item.name }}_redirect"
    state: present
    host: "{{ item.host }}"
    subdomains:
      - "{{ item.domain }}"
    site_apps:
      - ["{{ item.redirect_to_secure_app }}", "{{ item.url_path }}"]
    https: false
    login_name: "{{webfaction_user}}"
    login_password: "{{webfaction_passwd}}"
  with_items:
    - "{{ website.main }}"
    - "{{ website.static }}"
    - "{{ website.uploads }}"
